- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install python3, nodejs / npm and pm2"
  shell: |
    # installs python
    sudo apt install python3 -y
    sudo apt-get install curl -y
    # install nodejs and npm
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash - && \
      sudo apt-get install -y nodejs
    # install pm2
    sudo npm install pm2 -g

