- name: Copy tar file
  copy:
    src: "files/artifact.tar.gz"
    dest: "~/"

- name: "install tar"
  shell: |
    sudo apt-get install tar

- name: "extract artifact"
  shell: |
    mkdir -p backend
    cp artifact.tar.gz backend
    cd backend
    tar xvfz artifact.tar.gz
    ls

- name: "start app"
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start